version: '2'

services:
  selenium:
    container_name: 'selenium'
    restart: always
    image: 'selenium/standalone-chrome:3.141'
  
  scraper:
    build: .
    container_name: app
    restart: "no"
    environment:
      - PATH_TO_HTML=/html
    volumes:
      - ./html:/html
      - ./logs:/logs
      - ./src/dbconfig:/src/dbconfig
    depends_on:
      - selenium
    command:
      - python
      - src/rent_prices/main.py
      - --collection=rents