version: '2'

services:
  selenium:
    container_name: 'selenium'
    restart: always
    image: 'selenium/standalone-chrome:3.141'
  
  scraper:
    build: .
    container_name: app
    restart: always
    environment:
      - PATH_TO_HTML=/html
    volumes:
      - ./html:/html
    depends_on:
      - selenium